backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: blog
    label: Blog
    folder: "src/pages/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: experience
    label: Experience
    folder: "src/pages/experience"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "experience"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Company", name: "company", widget: "string"}
      - {label: "Start Date", name: "dateStart", widget: "datetime"}
      - {label: "End Date", name: "dateEnd", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}

  - name: education
    label: Education
    folder: "src/pages/education"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "education"}
      - {label: "Degree", name: "degree", widget: "string"}
      - {label: "School", name: "school", widget: "string"}
      - {label: "Graduation Year", name: "year", widget: "string"}
      - {label: "Major", name: "major", widget: "string"}
      - {label: "Minors", name: "minor", widget: "string"}

  - name: awards
    label: Awards
    folder: "src/pages/awards"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "awards"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}

  - name: skills
    label: Skills
    folder: "src/pages/skills"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "skills"}
      - {label: "Skill", name: "skill", widget: "string"}
      - {label: "Years", name: "years", widget: "string"}

  - name: interests
    label: Interests
    folder: "src/pages/interests"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "interests"}
      - {label: "Interests", name: "interests", widget: "list"}